/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 messageBox.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import messageScene from '../assets/messageBox.gltf'

export function MessageBox(props) {
  const { nodes, materials } = useGLTF(messageScene)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <pointLight intensity={1} decay={2} distance={2000} position={[-97.733, 24.202, 440.336]} />
        <directionalLight intensity={0.7} decay={2} rotation={[-0.746, 0.794, 0.914]} />
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[-18.767, 1042.073, 109.381]} rotation={[-1.43, 0.002, 0.015]} />
        <mesh geometry={nodes.Rectangle_3.geometry} material={nodes.Rectangle_3.material} position={[0, 200, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Rectangle_2.geometry} material={nodes.Rectangle_2.material} position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Rectangle.geometry} material={nodes.Rectangle.material} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload(messageScene)
